services:
  postgres:
    image: postgres:16-alpine
    container_name: personalsite_db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      ADMIN_PASSWORD_HASH: ${ADMIN_PASSWORD_HASH}
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build: 
      context: ./backend-java
      dockerfile: Dockerfile
    container_name: personalsite_api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres

volumes:
  pgdata: